name: pol-api-server development CI/CD

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  CI:
    environment: development
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Create environment file
        run: |
          touch .env
          echo JWT_KEY=${{ secrets.JWT_KEY }} >> .env
          echo LOG_MAX_COUNT=${{ secrets.LOG_MAX_COUNT }} >> .env
          echo LOG_MAX_SIZE=${{ secrets.LOG_MAX_SIZE }} >> .env
          echo LOG_PATH=${{ secrets.LOG_PATH }} >> .env
          echo REDIS_HOST=${{ secrets.REDIS_HOST }} >> .env
          echo REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} >> .env
          echo REDIS_PORT=${{ secrets.REDIS_PORT }} >> .env
          echo RELATION_DB_HOST=${{ secrets.RELATION_DB_HOST }} >> .env
          echo RELATION_DB_PASSWORD=${{ secrets.RELATION_DB_PASSWORD }} >> .env
          echo RELATION_DB_PORT=${{ secrets.RELATION_DB_PORT }} >> .env
          echo RELATION_DB_SCHEMA=${{ secrets.RELATION_DB_SCHEMA }} >> .env
          echo RELATION_DB_TYPE=${{ secrets.RELATION_DB_TYPE }} >> .env
          echo RELATION_DB_USER_NAME=${{ secrets.RELATION_DB_USER_NAME }} >> .env
          echo SOCIAL_GOOGLE_KEY=${{ secrets.SOCIAL_GOOGLE_KEY }} >> .env
          echo SOCIAL_GOOGLE_SECRET_KEY=${{ secrets.SOCIAL_GOOGLE_SECRET_KEY }} >> .env
          echo SOCIAL_KAKAO_KEY=${{ secrets.SOCIAL_KAKAO_KEY }} >> .env
          echo SOCIAL_KAKAO_SECRET_KEY=${{ secrets.SOCIAL_KAKAO_SECRET_KEY }} >> .env
          echo SOCIAL_NAVER_KEY=${{ secrets.SOCIAL_NAVER_KEY }} >> .env
          echo SOCIAL_NAVER_SECRET_KEY=${{ secrets.SOCIAL_NAVER_SECRET_KEY }} >> .env
          echo SOCIAL_REDIRECT_URI=${{ secrets.SOCIAL_REDIRECT_URI }} >> .env
          cat .env | head -n 1

      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile.dev -t pol-api .

      - name: Docker push
        run: |
          docker tag pol-api ${{ secrets.DOCKER_USERNAME }}/pol-api:${GITHUB_SHA::7}
          docker push ${{ secrets.DOCKER_USERNAME }}/pol-api:${GITHUB_SHA::7}
